In [1]:
import numpy as np

In [2]:
m=np.array([0.010111,0.0043532,0.0137058]).reshape(3,1)
m1=m[0]
m2=m[1]
m3=m[2]
R=0.011
a=np.array([0.00324625,0.00022983,0.00420395,0.00022983,0.00049937,0.00019247,0.00420395,0.00019247,0.00764897]).reshape(3,3)
b=np.linalg.inv(a)
b11=b[0][0]
b12=b[0][1]
b13=b[0][2]
b21=b[1][0]
b22=b[1][1]
b23=b[1][2]
b31=b[2][0]
b32=b[2][1]
b33=b[2][2]

In [5]:
#real
c11=b.sum()
c12=b.dot(m).sum()
c21=c12
c22=m.T.dot(b.dot(m))[0]
c13=2
c23=2*R

det=c11*c22-c12*c21
det_lambda=-(c12*c23-c22*c13)
det_eta=(c11*c23-c21*c13)
lambd=det_lambda/det
eta=det_eta/det

u1=0.5*b.dot(lambd*np.ones(3).reshape(3,1)+eta*m)
print(np.array(u1).reshape(1,-1))

[[0.45423611 0.11471805 0.43104584]]


In [17]:
#A
u2=np.array([0,((m3-R)/(m3-m2))[0],((R-m2)/(m3-m2))[0]])
u2

array([0.        , 0.28930992, 0.71069008])

In [18]:
#B
c11=(b11+b12+b13)
c12=b11
c21=(b21+b22+b23+b31+b32+b33)
c22=b21+b31
c13=0
c23=2

det=c11*c22-c12*c21
det_lambda=-(c12*c23-c22*c13)
det_mu1=(c11*c23-c21*c13)
lambd=det_lambda/det
mu1=det_mu1/det
print("mu1 is NEGATIVE",lambd,mu1)

mu=np.array([mu1,0,0]).reshape(3,1)
u3=0.5*b.dot(lambd*np.ones(3).reshape(3,1)+mu)
u3

mu1 is NEGATIVE 0.0009744754741479252 -0.0002006084442383491


array([[0.        ],
       [0.96046835],
       [0.03953165]])

In [22]:
print(u1.T.dot(a).dot(u1))
print(u2.T.dot(a).dot(u2))
print(u3.T.dot(a).dot(u3))

[[0.00378678]]
0.003984289480120709
[[0.00048724]]


In [23]:
u3.sum()

1.0000000000000002

In [27]:
print(u1.T.dot(m),R)
print(u2.T.dot(m),R)
print(u3.T.dot(m),R)

[[0.011]] 0.011
[0.011] 0.011
[[0.00472292]] 0.011
